# Generated by Django 5.0.6 on 2024-07-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
        ('store', '0002_cajasorpresa_detallespedido_producto_and_more'),
    ]

    operations = [
    ]
